# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  
  desc "Build and Test the app"
  lane :build_and_test do
  build_app(
    project: "GrckiKino.xcodeproj",
    scheme: "GrckiKino",
    xcargs: "-skipPackagePluginValidation -allowProvisioningUpdates"
  )
  scan(
    project: "GrckiKino.xcodeproj",
    scheme: "GrckiKino",
    xcargs: "-skipPackagePluginValidation"
  )
  end
  
  desc "Build and upload to TestFlight"
  lane :release do
  increment_build_number
  build_app(
    project: "GrckiKino.xcodeproj",
    scheme: "GrckiKino",
    export_method: "app-store", # or "ad-hoc", "enterprise", etc.
    xcargs: "-skipPackagePluginValidation -allowProvisioningUpdates"
  )
  upload_to_testflight(
    skip_waiting_for_build_processing: false, # set to true if you don't want to wait for the build processing to finish
    skip_submission: true, # set to false if you want to automatically submit the build to beta testers
    beta_app_feedback_email: "lazar89nis@gmail.com", # optional, replace with your email
  )
  end

  desc "build lane"
  lane :build do
  build_app(
    project: "GrckiKino.xcodeproj",
    scheme: "GrckiKino",
    xcargs: "-skipPackagePluginValidation -allowProvisioningUpdates"
  )
  end
  
  desc "Runs all the tests"
  lane :test do
    scan(
      project: "GrckiKino.xcodeproj",
      scheme: "GrckiKino",
      xcargs: "-skipPackagePluginValidation",
    )
  end
  
  desc  "Deploy app to App Store Connect"
  lane :deploy do
    match(type: "appstore", readonly: true)
    api_key = app_store_connect_api_key(
      key_id: "33F9ZFQN9Z",
      issuer_id: "69a6de7f-8312-47e3-e053-5b8c7c11a4d1",
      key_content: $APP_STORE_CONNECT_API_KEY_KEY,
      #key_content: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR1RBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJIa3dkd0lCQVFRZ3ZYU2RaUzI0N3c1MW01MysKNnllYjY4NmRBSEovNjNIbDlaTjhCK0lMQThlZ0NnWUlLb1pJemowREFRZWhSQU5DQUFRR21JY21YaUlTdFAzRwpRajB5SzE0eEZLdG41QVhYWVlRUko0QTZjQS8ycTduVTFUZUR2bnp6NUh1ZmRMMW9senlEblVMT1BQbVlySGNUCjFxcVM2WmFtCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=",
      is_key_content_base64: true
    )
    increment_build_number({
      build_number: latest_testflight_build_number(api_key: api_key) + 1
    })
    gym(export_options: "./GrckiKino/fastlane/ExportOptions.plist")
    deliver(
      api_key: api_key,
      force: true,
      skip_screenshots: true,
      precheck_include_in_app_purchases: false,
      automatic_release: false
    )
  end
end